'''
Accelera Consulting
Author: Accelera Team
Created on: 2024-06-17

This module contains functions for automatic binning and Weight of Evidence (WOE) transformation.
'''

import json
import pandas as pd
from pandas.api.types import is_numeric_dtype
import numpy as np
from helper import io_save_json, io_save_dataframe_as_csv
from logging_config.logger_config import get_logger


logger_name = "mlops.auto_binning_woe"
logger_file_name = "auto_binning_woe.log"
logger = get_logger(logger_name, logger_file_name)

def convert_pd_interval_to_str(
        interval: pd.Interval,
        round_apply: bool = True
        ) -> str:
    """
    Purpose
    -------
    Convert a pandas Interval object to a string representation.

    This function is used to convert the bin labels generated by pd.qcut or pd.cut,
    which are pandas Interval objects, into a more readable string format for reporting.
    What is pd.interval:
    Definition of ( and ] in pandas Interval:
    - ( means the interval does not include the left endpoint (open on the left).
    - ] means the interval includes the right endpoint (closed on the right).
        Therefore,
        [18, 25) means the interval includes the left endpoint but not the right endpoint

    Parameters
    ----------
    interval : pd.Interval
        The pandas Interval object to convert.

    Returns
    -------
    str
        A string representation of the interval in the format "(lower_bound, upper_bound]".
        example: pd.Interval(18, 25, closed="right") will be converted to "from_18_to_25".

    Note
    ----
    Called in:
    - Metadata returned by calculate_woe_iv_table function.
    """
    if not isinstance(interval, pd.Interval):
        logger.error("Input is not a pandas Interval.")
        raise ValueError("Input must be a pandas Interval.")
    
    lower_bound = interval.left
    upper_bound = interval.right
    closed = interval.closed
    logger.info(f"Converting Interval: {interval} with lower_bound={lower_bound}, upper_bound={upper_bound}, closed='{closed}' to string representation.")

    # Get Rounds of lower_bound and upper_bound if round_apply is True, otherwise keep them as they are
    if round_apply:
        lower_bound = int(round(lower_bound))
        upper_bound = int(round(upper_bound))
        logger.info(f"Rounded bounds: lower_bound={lower_bound}, upper_bound={upper_bound}")

    if closed == "right":
        return f"from_{lower_bound}_to_{upper_bound}"
    elif closed == "left":
        return f"from_{lower_bound}_to_{upper_bound}"
    elif closed == "both":
        return f"from_{lower_bound}_to_{upper_bound}"
    # if closed is neither, raise error because it is an invalid state for a pandas Interval
    elif closed == "neither":
        error_message = f"Invalid 'closed' attribute in Interval: {closed}. 'neither' is not a valid state for a pandas Interval."
        logger.error(error_message)
        raise ValueError(error_message)
    else:
        logger.error(f"Invalid 'closed' attribute in Interval: {closed}")
        raise ValueError(f"Invalid 'closed' attribute in Interval: {closed}")

def interpret_iv(iv: float) -> str:
    """
    Purpose
    -------
    Interpret the Information Value (IV) score based on commonly accepted thresholds.

    IV is a measure of the predictive power of a feature with respect to a binary target.
    The higher the IV, the stronger the relationship between the feature and the target.

    Parameters
    ----------
    iv : float
        The Information Value score to interpret.

    Returns
    -------
    str
        A string interpretation of the IV score:
        - "Not Predictive" for IV < 0.02
        - "Weak Predictive Power" for 0.02 <= IV < 0.1
        - "Medium Predictive Power" for 0.1 <= IV < 0.3
        - "Strong Predictive Power" for 0.3 <= IV < 0.5
        - "Suspiciously High Predictive Power (Potential Data Leakage or Overfitting)" for IV >= 0.5

    Note
    ----
    Called in:
    - Metadata returned by calculate_woe_iv_table function.
    """
    # Raise error if IV is negative, as IV should never be negative in a valid calculation
    if iv < 0:
        logger.error(f"Invalid IV value: {iv}. IV cannot be negative.")
        raise ValueError("IV cannot be negative.")
    if iv < 0.02:
        return "Not Predictive"
    elif iv < 0.1:
        return "Weak Predictive Power"
    elif iv < 0.3:
        return "Medium Predictive Power"
    elif iv < 0.5:
         return "Strong Predictive Power"
    else:
        return "Suspiciously High Predictive Power (Potential Data Leakage or Overfitting)"

def is_monotonic(s: pd.Series) -> bool:
    """
    Purpose
    -------
    Check whether a numeric pandas Series is monotonic increasing or
    monotonic decreasing.

    This function is used to validate whether the Bad Rate or WoE trend
    moves consistently in one direction across ordered bins.

    Parameters
    ----------
    s : pd.Series
        Numeric pandas Series to check.

    Returns
    -------
    bool
        True if the Series is either monotonic increasing or monotonic
        decreasing. Otherwise, False.

    Note
    ----
    Called in:
    - Rule 3: Bad Rate monotonicity check.
    - Rule 4: WoE monotonicity check.
    """
    if not isinstance(s, pd.Series):
        logger.error("Input is not a pandas Series.")
        raise ValueError("Input must be a pandas Series.")
    name_of_series = s.name if s.name is not None else "Unnamed Series"
    logger.info(f"Checking monotonicity for series: {name_of_series}")
    monotonic_increasing = s.is_monotonic_increasing
    monotonic_decreasing = s.is_monotonic_decreasing
    monotonic = monotonic_increasing or monotonic_decreasing
    logger.info(f"Series is monotonic increasing: {monotonic_increasing}")
    logger.info(f"Series is monotonic decreasing: {monotonic_decreasing}")
    logger.info(f"Series is monotonic: {monotonic}")
    return monotonic

def calculate_woe_iv_table(
    df: pd.DataFrame,
    bin_col: str,
    target: str,
    eps: float = 0.5,
    output_dir: str = None
) -> pd.DataFrame:
    """
    Purpose
    -------
    Calculate bin-level Good, Bad, Bad Rate, WoE and IV statistics.

    This function is the main calculation engine of the WoE binning process.
    It receives a dataframe where the feature has already been assigned into
    bins and produces the bin summary table.

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe containing the bin column and target column.

    bin_col : str
        Column name containing bin assignments.
        For numeric binning, this column usually contains pandas Interval
        categories generated by pd.qcut or pd.cut.

    target : str
        Binary target column.
        Expected convention:
        - 0 = Good
        - 1 = Bad
    
    eps : float, optional
        Smoothing constant added to good and bad counts to avoid division by zero. 
        eps is added to counts, not directly to rates. 
        eps is a common continuity correction that prevents infinite WoE when a bin has zero good or zero bad observations.

    Returns
    -------
    pd.DataFrame
        Bin-level summary table with the following columns:
        - bin column
        - total
        - good
        - bad
        - bad_rate
        - bin_pct
        - good_dist
        - bad_dist
        - woe
        - woe_display
        - iv

    Note
    ----
    Important:
    - `woe` is the real mathematical WoE value.
    - `woe_display` is `woe * 100` and is only for reporting.
    - IV is calculated using the real `woe`, not `woe_display`.

    Bins produced by pd.qcut or pd.cut are pandas Interval objects.
    Example:
    - pd.Interval(18, 25, closed="right") is displayed as (18, 25].

    Called in:
    - Initial WoE / IV calculation.
    - After every merge operation.
    - Final WoE / IV calculation.
    """
    logger.info(f"Calculating WoE / IV table for bin_col='{bin_col}'")

    tmp = df[[bin_col, target]].copy()

    # Group by bin and calculate total cound and bad count (assuming target=1 is bad so we can sum it to get bad count)
    summary = (
        tmp.groupby(bin_col, observed=False)[target]
        .agg(total="count", bad="sum")
        .reset_index()
    )

    # Add good count
    summary["good"] = summary["total"] - summary["bad"]
    # Add bad rate
    summary["bad_rate"] = summary["bad"] / summary["total"]
    # Add bin percentage
    summary["bin_pct"] = summary["total"] / summary["total"].sum()

    # Calculate total good and total bad for the entire dataset (used for WoE and IV calculation)
    total_good = summary["good"].sum()
    total_bad = summary["bad"].sum()
    logger.info(f"Total good: {total_good} and % of total: {total_good / (total_good + total_bad):.2%}, Total bad: {total_bad} and % of total: {total_bad / (total_good + total_bad):.2%}")

    # NOTE: We apply smoothing to avoid division by zero in WoE calculation.
    # Formula for WoE: ln((good_dist) / (bad_dist))
    # If good_dist or bad_dist is zero, we get division by zero and WoE becomes infinite.
    # To prevent this, we add a small constant (eps) to both the numerator and denominator.
    # eps is added to counts, not directly to rates. 
    logger.info(f"Applying smoothing with eps={eps} to avoid division by zero in WoE calculation.")

    # Add Good Distribution (good_dist) with smoothing
    summary["good_dist"] = (
        (summary["good"] + eps) / (total_good + eps * len(summary))
    )
    logger.info("Good distribution calculated with smoothing:")
    for _, row in summary.iterrows():
        logger.info(f"Bin: {row[bin_col]}, Good count: {row['good']}, Good dist: {row['good_dist']:.6f}")
    
    # Calculate bad distribution with smoothing
    summary["bad_dist"] = (
        (summary["bad"] + eps) / (total_bad + eps * len(summary))
    )
    logger.info("Bad distribution calculated with smoothing:")
    for _, row in summary.iterrows():
        logger.info(f"Bin: {row[bin_col]}, Bad count: {row['bad']}, Bad dist: {row['bad_dist']:.6f}")

    # Add Odds Ratio (OR)
    summary["odds_ratio"] = summary["good_dist"] / summary["bad_dist"]
    logger.info("Odds Ratio calculated for each bin:")
    for _, row in summary.iterrows():
        logger.info(f"Bin: {row[bin_col]}, Odds Ratio: {row['odds_ratio']:.6f}")

    # Calculate WoE using the smoothed good_dist and bad_dist
    summary["woe"] = np.log(summary["odds_ratio"])
    logger.info("WoE calculated for each bin:")
    for _, row in summary.iterrows():
        logger.info(f"Bin: {row[bin_col]}, WoE: {row['woe']:.6f}, Display WoE: {row['woe'] * 100:.2f}")
    summary["woe_display"] = summary["woe"] * 100

    # Calculate good_dist - bad_dist component for transparency in IV calculation
    summary["good_dist_minus_bad_dist"] = summary["good_dist"] - summary["bad_dist"]
    logger.info("Good Distribution - Bad Distribution calculated for each bin:")
    for _, row in summary.iterrows():
        logger.info(f"Bin: {row[bin_col]}, Good_Dist: {row['good_dist']:.6f}, Bad_Dist: {row['bad_dist']:.6f}, Difference: {row['good_dist_minus_bad_dist']:.6f}")

    summary["iv"] = (
        (summary["good_dist"] - summary["bad_dist"]) * summary["woe"]
    )
    logger.info("IV contribution calculated for each bin:")
    for _, row in summary.iterrows():
        logger.info(f"Bin: {row[bin_col]}, IV contribution: {row['iv']:.6f}")
    
    # Human readable bin labels for reporting (e.g., "from_18_to_25" instead of "(18, 25]")
    summary["human_readable_bin"] = summary[bin_col].apply(convert_pd_interval_to_str)

    column_order = [
        bin_col,
        "human_readable_bin",
        "total",
        "good",
        "bad",
        "bad_rate",
        "bin_pct",
        "good_dist",
        "bad_dist",
        "good_dist_minus_bad_dist",
        "odds_ratio",
        "woe",
        "woe_display",
        "iv"
    ]

    logger.info(
        f"WoE / IV table calculated. Bin count={len(summary)}, Total IV={summary['iv'].sum():.6f}"
    )

    # Reorder columns for better readability in the output table
    summary_reordered = summary[column_order]

    # Calculate total IV for the feature by summing the IV contributions from all bins
    total_iv = summary["iv"].sum()
    total_iv_interpretation = interpret_iv(total_iv)
    logger.info(f"Total IV for the feature: {total_iv:.6f}")
    logger.info(f"Interpretation of Total IV: {total_iv_interpretation}")

    logger.info("FINAL WOE TABLE:")
    logger.info(f"\n{summary_reordered.to_string(index=False)}")

    # Prepare metadata of Woe and Bins
    # Convert the entire summary table to dict for metadata, converting Interval objects to strings
    summary_for_metadata = summary_reordered.copy()
    summary_for_metadata[bin_col] = summary_for_metadata[bin_col].astype(str)
    
    metadata = {
        "binCol": bin_col,
        "target": target,
        "eps": eps,
        "summaryTable": summary_for_metadata.to_dict('records'),
        "totalIv": total_iv,
        "interpretIv": total_iv_interpretation,
        "numberofBins": len(summary_reordered)
    }

    # Save metadata to JSON file if output_dir is provided
    if output_dir is not None:
        metadata_output_path = f"{output_dir}/woe_iv_metadata.json"
        logger.info(f"Saving WoE / IV metadata to {metadata_output_path}")
        saved_path = io_save_json(metadata, metadata_output_path) 
        logger.info(f"WoE / IV metadata saved successfully to {saved_path}")

        csv_output_path = f"{output_dir}/woe_iv_summary_table.csv"
        logger.info(f"Saving WoE / IV summary table to {csv_output_path}")
        saved_path = io_save_dataframe_as_csv(summary_reordered.drop(columns=[bin_col], inplace=False), csv_output_path)
        logger.info(f"WoE / IV summary table saved successfully to {saved_path}")

    return summary_reordered, metadata

def create_initial_bins(
    df: pd.DataFrame,
    feature: str,
    series: pd.Series = None,
    initial_bins: int = 20
) -> pd.Series:
    """
    Purpose
    -------
    Create initial bins for a numeric feature.

    The function first tries to create quantile-based bins using pd.qcut.
    If qcut fails, it falls back to pd.cut.

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe.

    feature : str
        Numeric feature to be binned.
    
    series : pd.Series, optional
        Optional pandas Series containing the feature values. If not provided, the function will use df[feature].

    initial_bins : int, optional
        Requested number of initial bins.
        Default is 20.

    Returns
    -------
    pd.Series
        Categorical Series containing initial bin assignments.

    Note
    ----
    pd.qcut and pd.cut return categorical bins whose categories are pandas
    Interval objects.

    Example category:
    - pd.Interval(18, 25, closed="right")
    - Displayed as: (18, 25]

    Called in:
    - Initial bin creation step before Rule 1.
    """
    if series is not None:
        feature = series.name if series.name is not None else "Unnamed Series"
        logger.info(f"Using provided series for binning. Feature='{feature}', requested_bins={initial_bins}")
        x = series
        logger.info(f"Input pandas data type: {type(x).__name__}, number of records: {len(x)}, Shape: {x.shape}")
    else:
        all_cıolumns = df.columns.tolist()
        all_columns_str = ", ".join(all_cıolumns)
        logger.info(f"All columns in the dataframe: {all_columns_str}")
        if feature is None:
            logger.error("Feature name must be provided if series is not provided.")
            raise ValueError("Feature name must be provided if series is not provided.")
        if feature not in df.columns:
            logger.error(f"Feature '{feature}' not found in dataframe columns.")
            raise ValueError(f"Feature '{feature}' not found in dataframe columns.")
        logger.info(f"Creating initial bins. Feature='{feature}', requested_bins={initial_bins}")
        x = df[feature]
        logger.info(f"Input pandas data type: {type(x).__name__}, number of records: {len(x)}, Shape: {x.shape}")

    try:
        # Apply pd.qcut to create quantile-based bins. If there are duplicate edges, it will raise a ValueError.
        bins = pd.qcut(
            x,
            q=initial_bins,
            duplicates="drop"
        )

        logger.info(f"Initial bins created with qcut. Feature: {feature}")
        logger.info("Bins:")
        for bin in bins.cat.categories:
            logger.info(f"  - {bin}: {bin.left} to {bin.right}, closed='{bin.closed}' Number of records in this bin: {(bins == bin).sum()}")

    except Exception as e:
        warning_message = f"qcut failed for feature '{feature}' with error: {str(e)}. Falling back to cut."
        logger.warning(warning_message)

        # If qcut fails, we fall back to cut which creates equal-width bins. We use the same number of bins as requested, but cut will automatically adjust if there are duplicate edges.
        bins = pd.cut(
            x,
            bins=initial_bins,
            duplicates="drop"
        )

        logger.info(f"Initial bins created with cut. Feature: {feature}")
        logger.info("Bins:")
        for bin in bins.cat.categories:
            logger.info(f"  - {bin}: {bin.left} to {bin.right}, closed='{bin.closed}' Number of records in this bin: {(bins == bin).sum()}")

    return bins

def merge_intervals(
    intervals: list[pd.Interval],
    i: int
) -> list[pd.Interval]:
    """
    Purpose
    -------
    Merge two adjacent pandas Interval bins.

    The function merges intervals[i] and intervals[i + 1] into a single
    wider interval.

    Parameters
    ----------
    intervals : list[pd.Interval]
        Ordered list of current pandas Interval bins.

    i : int
        Left index of the adjacent pair to merge.

    Returns
    -------
    list[pd.Interval]
        Updated ordered interval list after merging.

    Note
    ----
    The interval list usually comes from:
    - data["_bin"].cat.categories

    Example:
    Input:
    - (18, 25] -> Index 0
    - (25, 35] -> Index 1
    - (35, 50] -> Index 2

    merge_intervals(intervals, 1) -> removing 35 from the bin edges.

    So,
    - (25, 35] -> Index 1 (given paramerer i=1)
    - (35, 50] -> Index 2 (given parameter i+1=2)

    and we remove the boundary at 35 and merge these two intervals into one interval.
    
    then,
    
    Output:
    - (18, 25]
    - (25, 50]

    Conceptually, this removes one boundary:
    - 18 | 25 | 35 | 50
    - 18 | 25 | 50

    Called in:
    - Rule 1: Small bin merge.
    - Rule 2: Zero good / zero bad merge.
    - Rule 3: Bad Rate monotonicity merge.
    - Rule 4: WoE monotonicity merge.
    - Rule 5: Maximum bin count merge.
    """
    logger.info(f"Merging intervals at index pair=({i}, {i + 1})")

    # Input is not a list of pandas Interval objects, raise error
    if not isinstance(intervals, list) or not all(isinstance(interval, pd.Interval) for interval in intervals):
        logger.error("Input intervals must be a list of pandas Interval objects.")
        raise ValueError("Input intervals must be a list of pandas Interval objects.")
    
    logger.info(f"Current intervals before merge (count={len(intervals)}):")
    for idx, interval in enumerate(intervals):
        if idx in [i, i + 1]:
            logger.info(f"  - Index {idx}: {interval} (left={interval.left}, right={interval.right}, closed='{interval.closed}') <-- to be merged")
        else:
            logger.info(f"  - Index {idx}: {interval} (left={interval.left}, right={interval.right}, closed='{interval.closed}')")

    new_intervals = []

    for idx, interval in enumerate(intervals):
        if idx == i:
            left = intervals[i].left
            right = intervals[i + 1].right
            closed = intervals[i].closed
            logger.info(f"Merging intervals at index pair=({i}, {i + 1}):")
            logger.info(f"  - {intervals[i]} and {intervals[i + 1]} into new interval with left={left}, right={right}, closed='{closed}'")
            # Create the merged interval.
            merged_interval = pd.Interval(left, right, closed=closed)
            logger.info(f"  - Created merged interval ---> {merged_interval}")

            # Append the merged interval to the new intervals list
            new_intervals.append(merged_interval)

        elif idx == i + 1:
            logger.info(f"Skipping interval at index {idx} since it has been merged: {intervals[i + 1]}")
            continue

        else:
            logger.info(f"Keeping interval at index {idx} unchanged: {interval}")
            new_intervals.append(interval)

    logger.info(f"Intervals merged. Previous count={len(intervals)}, New count={len(new_intervals)}")
    logger.info("New intervals:")
    for idx, interval in enumerate(new_intervals):
        logger.info(f"  - Index {idx}: {interval} (left={interval.left}, right={interval.right}, closed='{interval.closed}')")

    logger.info(f"Merge Completed - REMOVED ITEM: {intervals[i].right}")

    return new_intervals

def assign_bins_from_intervals(
    x: pd.Series,
    intervals: list[pd.Interval]
) -> pd.Categorical:
    """
    Purpose
    -------
    Assign numeric values to the current pandas Interval list.

    This function is used after merge operations to reassign all observations into the updated interval structure.

    Basically, we say that I have new updated intervals after a merge, and 
    I want to reassign all my numeric observations (my original data) into these new intervals without running pd.qcut again.

    Parameters
    ----------
    x : pd.Series
        Numeric feature values.

    intervals : list[pd.Interval]
        Current ordered list of pandas Interval bins.

    Returns
    -------
    pd.Categorical
        Ordered categorical bin assignments based on the supplied interval list.

    Note
    ----
    This function does not run pd.qcut again.

    After a merge, the algorithm preserves the updated interval boundaries
    and only reassigns observations into the current intervals.

    Example:
    Current intervals:
    - (18, 25]
    - (25, 50]
    - (50, 80]

    But in the original data, we have old intervals that were assigned by pd.qcut before the merge, for example:
    - (18, 25]
    - (25, 35] -> this interval was merged with the next one
    - (35, 50] -> this interval was merged with the previous one
    - (50, 80]

    So we reassign observations into the new intervals based on the updated interval structure.

    Called in:
    - After every merge operation.
    - Before recalculating WoE / IV.
    - Final bin assignment step.
    """
    logger.info(f"Assigning observations to current intervals. Interval count={len(intervals)}")

    # We create an empty Series to hold the assigned bins. 
    # We will fill this Series by checking which interval each observation falls into.
    result = pd.Series(index=x.index, dtype="object")

    for interval in intervals:
        # We create a boolean mask to identify which observations in x fall into the current interval.
        mask = x.apply(lambda v: pd.notna(v) and v in interval)
        # We assign the current interval to all observations that fall into it.
        result.loc[mask] = interval
    
    logger.info("Observations assigned to intervals:")
    for interval in intervals:
        count_in_interval = (result == interval).sum()
        logger.info(f"\tInterval: {interval} (left={interval.left}, right={interval.right}, closed='{interval.closed}')")
        logger.info(f"\t\tCount of observations assigned: {count_in_interval}")
    
    # Finally, we convert the result Series into a pandas Categorical with the specified intervals as categories and ordered=True to maintain the order of bins.
    new_bins = pd.Categorical(
        result,
        categories=intervals,
        ordered=True # This ensures that the bins are treated as ordered categories, which is important for monotonicity checks and other operations that rely on the order of bins.
    )
    logger.info(f"Assigning New Bins Completed, returned pandas data type: {type(new_bins).__name__}")
    return new_bins

def find_closest_neighbor(
    summary: pd.DataFrame,
    idx: int,
    metric: str = "bad_rate"
) -> int:
    """
    Purpose
    -------
    Find the closest adjacent neighbor of a problematic bin.

    This function is used when a specific bin is problematic and needs to be merged with either its left or right neighbor.

    Parameters
    ----------
    summary : pd.DataFrame
        Current bin summary table.

    idx : int
        Index of the problematic bin.

    metric : str, optional
        Metric used for comparing neighboring bins.
        Default is "bad_rate".
        Example:
        - A: bad_rate = 10%
        - B: bad_rate = 11% (problematic bin, index 1)
        - C: bad_rate = 30%
        Calculation of Differences:
        - Left difference = abs(11% - 10%) = 1%
        - Right difference = abs(30% - 11%) = 19%
        So, we select Bin A to merge with Bin B because it has a smaller difference in bad_rate compared to Bin C.

    Returns
    -------
    int
        Index of the left bin in the pair to be merged.
        Example:
        0: A
        1: B  <- problematic bin
        2: C
        A and B will be merged. merge_idx = 0 (merge_intervals called with i=0)
        0: A
        1: B
        2: C  <- problematic bin
        3: D
        C and D will be merged. merge_idx = 2 (merge_intervals called with i=2)
        We return always left index number of MERGED PAIR.

    Note
    ----
    Example 1:
    Bad rates:
    - Bin A = 10%
    - Bin B = 11% (problematic bin, index 1)
    - Bin C = 30%
    The function selects A-B merge and returns the left index of A.
    So, it returns index of Bin A, which is the left index of the pair to be merged (A-B).
    Becasue merged function merges intervals at index i and i+1, so if we return index of Bin A, 
    which is the left index of the pair to be merged (A-B), then merge_intervals will merge A and B together.

    Example 2:
    Bad rates:
    - Bin A = 10%
    - Bin B = 30% (problematic bin, index 1)
    - Bin C = 31%
    The function selects B-C merge and returns the left index of B.
    So, it returns index of Bin B, which is the left index of the pair to be merged (B-C).

    For other situations:
    - If the problematic bin is the first bin, it can only merge with the right neighbor, so it returns its own index.
        Example:
        Bad rates:
        - Bin A = 30% (problematic bin, index 0)
        - Bin B = 10%
        - Bin C = 20%
        Since Bin A is the first bin, it can only merge with Bin B, so it returns index 0 (the index of Bin A).
    - If the problematic bin is the last bin, it can only merge with the left neighbor, so it returns the index of the left neighbor.
        Example:
        Bad rates:
        - Bin A = 10%
        - Bin B = 20%
        - Bin C = 30% (problematic bin, index 2)
        Since Bin C is the last bin, it can only merge with Bin B, so it returns index 1 (the index of Bin B, which is the left neighbor of Bin C).

    Called in:
    - Rule 1: Small bin merge.
    - Rule 2: Zero good / zero bad merge.
    """
    # Raise Error if idx is negative or greater than the last index of summary
    if idx < 0 or idx >= len(summary):
        logger.error(f"Invalid idx: {idx}. It must be between 0 and {len(summary) - 1}.")
        raise ValueError(f"Invalid idx: {idx}. It must be between 0 and {len(summary) - 1}.")

    logger.info(f"Finding closest neighbor. Problem bin index={idx}, metric={metric}")

    # If the problematic bin is the first bin, it can only merge with the right neighbor, so we return its own index.
    if idx == 0:
        logger.info(f"Problematic bin is the first bin. It can only merge with the right neighbor. Selected neighbor index={idx}")
        return 0

    # If the problematic bin is the last bin, it can only merge with the left neighbor, so we return the index of the left neighbor.
    if idx == len(summary) - 1:
        logger.info(f"Problematic bin is the last bin. It can only merge with the left neighbor. Selected neighbor index={idx - 1}")
        return idx - 1

    # For other situations, we compare the metric values of the left and right neighbors and select the one that is closer to the problematic bin.
    left_diff = abs(summary.loc[idx, metric] - summary.loc[idx - 1, metric])
    right_diff = abs(summary.loc[idx, metric] - summary.loc[idx + 1, metric])
    logger.info(f"Left neighbor index={idx - 1}, {metric}={summary.loc[idx - 1, metric]:.6f}, diff with problem bin: {left_diff:.6f}")
    logger.info(f"Right neighbor index={idx + 1}, {metric}={summary.loc[idx + 1, metric]:.6f}, diff with problem bin: {right_diff:.6f}")

    if left_diff <= right_diff:
        merge_idx = idx - 1
        logger.info(f"Left neighbor is closer or equal. Selected left neighbor index={merge_idx}")
    else:
        merge_idx = idx
        logger.info(f"Right neighbor is closer. Selected left neighbor index={merge_idx}")

    logger.info(f"Closest neighbor found.")
    logger.info(f"\t\tProblem bin index={idx}")
    logger.info(f"\t\tNeighbor index to merge with={merge_idx}")

    return merge_idx

def find_most_similar_adjacent_pair(
    summary: pd.DataFrame,
    metric: str = "bad_rate"
) -> int:
    """
    Purpose
    -------
    Find the most similar adjacent bin pair.

    This function is used when one merge is needed and the algorithm wants to minimize information loss by merging the most similar neighboring bins.
    Question: Which pair of adjacent bins is the most similar in terms of a specific metric (e.g., bad_rate)?

    Difference from find_closest_neighbor function:
    - find_closest_neighbor is used when we have a specific problematic bin and we want to find the closest neighbor for that specific bin to merge with.
    - find_most_similar_adjacent_pair is used when we just want to find the most similar adjacent pair in the entire summary table without focusing on a specific problematic bin. 
    It is more of a global comparison to find the pair of bins that are closest to each other in terms of the specified metric.

    Parameters
    ----------
    summary : pd.DataFrame
        Current bin summary table.

    metric : str, optional
        Metric used for similarity comparison.
        Default is "bad_rate".

    Returns
    -------
    int
        Left index of the most similar adjacent pair.

    Note
    ----
    Example:
    Bad rates:
    - B1 = 10%
    - B2 = 11%
    - B3 = 35%

    Differences:
    - B1-B2 = 1%
    - B2-B3 = 24%

    The function selects B1-B2.

    Called in:
    - Rule 5: Maximum bin count reduction.
    - Fallback for Rule 3 or Rule 4 if no violation pair is found.
    """
    logger.info(f"Finding most similar adjacent pair. Metric={metric}")

    diffs = []

    for i in range(len(summary) - 1):
        diff = abs(summary.loc[i, metric] - summary.loc[i + 1, metric])
        val_i = summary.loc[i, metric]
        val_i_plus_1 = summary.loc[i + 1, metric]
        logger.info(f"  Index {i} <-> {i + 1} | {metric}: {val_i:.6f} → {val_i_plus_1:.6f} | Difference = {diff:.6f}")
        diffs.append((i, diff))

    merge_idx = min(diffs, key=lambda x: x[1])[0]
    min_diff = min(diffs, key=lambda x: x[1])[1]
    logger.info(f"Best pair found: Index {merge_idx} <-> {merge_idx + 1} with smallest difference = {min_diff:.6f}")

    logger.info(f"Returning left index of the most similar adjacent pair to merge: {merge_idx}")

    return merge_idx

def find_monotonicity_violation_pair(
    summary: pd.DataFrame,
    metric: str = "bad_rate"
) -> int | None:
    """
    Purpose
    -------
    Find an adjacent pair that violates monotonicity.

    The function checks both monotonic directions:
    - increasing
    - decreasing

    It selects the direction with fewer violations and returns the closest
    violating adjacent pair.

    Parameters
    ----------
    summary : pd.DataFrame
        Current bin summary table.

    metric : str, optional
        Metric used for monotonicity evaluation.
        Default is "bad_rate".

    Returns
    -------
    int or None
        Left index of the violating adjacent pair.
        Returns None if no violation exists.

    Note
    ----
    Example:
    Bad rates:
    - 5%
    - 10%
    - 8%
    - 20%

    The pair 10% -> 8% violates increasing monotonicity.
    The function returns the left index of that pair.

    Called in:
    - Rule 3: Bad Rate monotonicity merge.
    - Rule 4: WoE monotonicity merge.
    """
    logger.info(f"Finding monotonicity violation pair. Metric={metric}")

    values = summary[metric].values

    inc_violations = []
    dec_violations = []

    for i in range(len(values) - 1):
        if values[i] > values[i + 1]:
            inc_violations.append(i)

        if values[i] < values[i + 1]:
            dec_violations.append(i)
        
        if values[i] == values[i + 1]:
            logger.info(f"Adjacent bins at indices {i} and {i + 1} have equal {metric} values ({values[i]:.6f}). This does not violate monotonicity in either direction.")
    
    logger.info(f"increasing monotonicity violations at indices: {inc_violations}")
    logger.info(f"decreasing monotonicity violations at indices: {dec_violations}")

    # We select the direction with fewer violations to minimize information loss.
    # Example:
    # Bad rates:
    # - 5%   (index 0)
    # - 10%  (index 1)
    # - 8%   (index 2)
    # - 20%  (index 3)
    # increasing monotonicity violations at indices: [1] (10% -> 8%)
    # decreasing monotonicity violations at indices: [0, 2] (5% -> 10% and 8% -> 20%)
    # inc_violations = [1]
    # dec_violations = [0, 2]
    # len(inc_violations) = 1 len(dec_violations) = 2 
    # Decision: len(inc_violations) <= len(dec_violations) → True 
    # So we select increasing monotonicity violations and we will merge the pair at index 1 (10% -> 8%) to fix that violation.

    # Set the violations list to the selected monotonicity direction
    if len(inc_violations) <= len(dec_violations):
        violations = inc_violations # Selected violations are increasing monotonicity violations
        logger.info(f"Selected increasing monotonicity violations.")
    else:
        violations = dec_violations # Selected violations are decreasing monotonicity violations
        logger.info(f"Selected decreasing monotonicity violations.")

    # If the selected violation list is empty, monotonicity is already satisfied.
    # Assume that,
    # Bad rates:
    # - 5%   (index 0)
    # - 10%  (index 1)
    # - 15%  (index 2)
    # - 20%  (index 3)
    # 5 -> 10% (increasing monotonicity satisfied)
    # 10% -> 15% (increasing monotonicity satisfied)
    # 15% -> 20% (increasing monotonicity satisfied)
    # increasing monotonicity violations at indices: []
    # decreasing monotonicity violations at indices: [0, 1, 2] (5% -> 10%, 10% -> 15%, 15% -> 20%)
    # So, you go this if clause ->
    # if len(inc_violations) <= len(dec_violations): -> True (0 <= 3)
    # violations = inc_violations -> violations = [] it means Monotonicity is OK.
    if not violations:
        logger.info("No monotonicity violation found.")
        return None

    merge_idx = min(
        violations,
        key=lambda i: abs(summary.loc[i, metric] - summary.loc[i + 1, metric])
    )

    logger.info(f"Monotonicity violation pair selected. Merge pair=({merge_idx}, {merge_idx + 1})")
    logger.info(f"Returning left index of the violating adjacent pair to merge: {merge_idx}")

    return merge_idx

def check_binning_quality(
    summary: pd.DataFrame,
    min_bin_pct: float = 0.05,
    max_bins: int = 10,
    min_bins: int = 3
) -> dict:
    """
    Purpose
    -------
    Check final binning quality rules.

    This function validates whether the final binning output satisfies the
    main business and statistical requirements for scorecard-style WoE binning.

    Parameters
    ----------
    summary : pd.DataFrame
        Final bin summary table.

    min_bin_pct : float, optional
        Minimum allowed observation ratio per bin.
        Default is 0.05.

    max_bins : int, optional
        Maximum allowed final bin count.
        Default is 10.

    min_bins : int, optional
        Minimum allowed final bin count.
        Default is 3.

    Returns
    -------
    tuple
        Tuple of (checks, checks_formatted) where:
        - checks: dict with boolean values for logic decisions
        - checks_formatted: dict with formatted strings for reporting

    Note
    ----
    Rules checked:
    - Rule 1: Minimum bin size.
    - Rule 2: Good and bad exist in every bin.
    - Rule 3: Bad Rate monotonicity.
    - Rule 4: WoE monotonicity.
    - Rule 5: Maximum bin count.
    - Rule 6: Minimum bin count.
    - Rule 7: IV reasonability.
    """
    logger.info(f"Checking final binning quality with min_bin_pct={min_bin_pct}, max_bins={max_bins}, and min_bins={min_bins}.")

    total_iv = summary["iv"].sum()
    logger.info(f"Total IV for the binned feature: {total_iv:.6f}")

    # Set variables for each rule check
    min_bin_pct_ok = (summary["bin_pct"] >= min_bin_pct).all()
    good_bad_exist_ok = ((summary["good"] > 0) & (summary["bad"] > 0)).all()
    bad_rate_monotonic_ok = is_monotonic(summary["bad_rate"])
    woe_monotonic_ok = is_monotonic(summary["woe"])
    bin_count_ok = (len(summary) <= max_bins) and (len(summary) >= min_bins)
    iv_reasonable_ok = 0.02 <= total_iv <= 0.50

    logger.info("-- Binning Quality Check Results --")
    logger.info(f"\tMinimum bin percentage check passed: {min_bin_pct_ok}")
    logger.info(f"\tGood and bad existence check passed: {good_bad_exist_ok}")
    logger.info(f"\tBad Rate monotonicity check passed: {bad_rate_monotonic_ok}")
    logger.info(f"\tWoE monotonicity check passed: {woe_monotonic_ok}")
    logger.info(f"\tBin count check passed: {bin_count_ok}")
    logger.info(f"\tIV reasonability check passed: {iv_reasonable_ok}")
    logger.info("-- End of Binning Quality Check Results --")

    # Boolean checks for logic
    checks = {
        "min_bin_pct_ok": min_bin_pct_ok,
        "good_bad_exist_ok": good_bad_exist_ok,
        "bad_rate_monotonic_ok": bad_rate_monotonic_ok,
        "woe_monotonic_ok": woe_monotonic_ok,
        "bin_count_ok": bin_count_ok,
        "iv_reasonable_ok": iv_reasonable_ok
    }

    # Formatted checks for reporting
    checks_formatted = {
        "minBinPct": f"{min_bin_pct_ok} <- Is minimum pct of each bin > {min_bin_pct}?",
        "goodBadExist": f"{good_bad_exist_ok} <- Do good and bad exist in every bin?",
        "badRateMonotonic": f"{bad_rate_monotonic_ok} <- Is Bad Rate monotonic?",
        "woeMonotonic": f"{woe_monotonic_ok} <- Is WoE monotonic?",
        "binCount": f"{bin_count_ok} <- Are bins between {min_bins} and {max_bins}?",
        "ivReasonable": f"{iv_reasonable_ok} <- Is IV {total_iv:.6f} reasonable? (0.02 < IV < 0.50)"
    }

    logger.info("Final binning quality check completed.")

    return checks, checks_formatted

def auto_woe_binning_numeric(
    df: pd.DataFrame,
    feature: str,
    target: str,
    initial_bins: int = 20,
    min_bin_pct: float = 0.05,
    max_final_bins: int = 10,
    min_final_bins: int = 3,
    min_iv: float = 0.02,
    max_iv: float = 0.50,
    max_iter: int = 100
) -> dict:
    """
    Purpose
    -------
    Automatically perform monotonic WoE binning for a numeric variable.

    The algorithm starts with quantile-based initial bins, calculates WoE / IV,
    and then iteratively merges adjacent bins until the required binning rules
    are satisfied.

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe.

    feature : str
        Numeric feature to be binned.

    target : str
        Binary target variable.
        Expected convention:
        - 0 = Good
        - 1 = Bad

    initial_bins : int, optional
        Number of initial qcut bins.
        Default is 20.

    min_bin_pct : float, optional
        Minimum allowed observation ratio per bin.
        Default is 0.05.

    max_final_bins : int, optional
        Maximum allowed number of final bins.
        Default is 8.

    min_iv : float, optional
        Minimum acceptable Information Value.
        Default is 0.02.

    max_iv : float, optional
        Maximum acceptable Information Value.
        Values above this level may indicate leakage.
        Default is 0.50.

    max_iter : int, optional
        Maximum number of merge iterations.
        Default is 100.

    Returns
    -------
    dict
        Dictionary containing:
        - feature
        - summary
        - total_iv
        - checks
        - status
        - final_intervals

    Note
    ----
    This function supports numeric features only.

    Initial bins are created with pd.qcut. The resulting bin categories are
    pandas Interval objects.

    After a merge, pd.qcut is not executed again. The current pandas Interval
    boundaries are preserved, and observations are reassigned to the updated
    intervals.

    Algorithm rules:
    - Rule 1: Merge bins with insufficient observation ratio.
    - Rule 2: Merge bins where good = 0 or bad = 0.
    - Rule 3: Enforce Bad Rate monotonicity.
    - Rule 4: Enforce WoE monotonicity.
    - Rule 5: Reduce bin count if final bin count is greater than max_final_bins.
    - Rule 6: Review IV range and assign final status.

    Raises
    ------
    ValueError
        If the supplied feature is not numeric.
    """
    logger.info(f"Starting numeric WoE auto binning. Feature:{feature}, Target:{target}")

    # Raise error if feature and target are the same, since they cannot be identical.
    if feature == target:
        error_message = (f"Feature Name: {feature} and Target Name: {target} cannot be the same. Please provide different feature and target columns.")
        logger.error(error_message)
        raise ValueError(error_message)

    # Raise error if the feature is not numeric, since this function only supports numeric features.
    if not is_numeric_dtype(df[feature]):
        error_message = (f"Feature: {feature} is not numeric, auto_woe_binning_numeric only supports numeric features.")
        logger.error(error_message)
        raise ValueError(error_message)

    # Raise error if the feature contains infinite values, since infinite values cannot be binned and will cause errors in the binning process.
    if np.isinf(df[feature]).any():
        error_message = (f"Feature: {feature} contains infinite values, which cannot be binned. Please handle infinite values before applying auto_woe_binning_numeric.")
        logger.error(error_message)
        raise ValueError(error_message)

    # Raise error if the feature contains NULL values, since NULL values cannot be binned and will cause errors in the binning process.
    if df[feature].isnull().any():
        error_message = (f"Feature: {feature} contains NULL values, which cannot be binned. Please handle NULL values before applying auto_woe_binning_numeric.")
        logger.error(error_message)
        raise ValueError(error_message)

    # Raise error if feature is constant, since a constant feature cannot be binned and will cause errors in the binning process.
    if df[feature].nunique() == 1:
        error_message = (f"Feature: {feature} is constant, which cannot be binned. Please remove or handle constant features before applying auto_woe_binning_numeric.")
        logger.error(error_message)
        raise ValueError(error_message)
    
    # Raise error if feature have only 2 unique valyes, since a feature with only 2 unique values cannot be binned further and will cause errors in the binning process.
    if df[feature].nunique() == 2:
        error_message = (f"Feature: {feature} has only 2 unique values, which cannot be binned further. Please handle it as a Flag Variable Logic.")
        logger.error(error_message)
        raise ValueError(error_message)
    
    # Raise error if feature unique values are less than initial_bins, since we cannot create more bins than unique values.
    if df[feature].nunique() < initial_bins:
        error_message = (f"Feature: {feature} has only {df[feature].nunique()} unique values, which is less than the requested initial_bins={initial_bins}. Please reduce initial_bins or handle the feature differently.")
        logger.error(error_message)
        raise ValueError(error_message)
    
    # Raise error if target variable is not binary, since WoE binning is designed for binary classification problems and requires a binary target variable.
    if df[target].nunique() != 2:
        error_message = (f"Target variable: {target} is not binary, WoE binning requires a binary target variable. Please ensure the target variable has exactly two unique values before applying auto_woe_binning_numeric.")
        logger.error(error_message)
        raise ValueError(error_message)

    # Raise error if target is binary but not in the expected format (0 and 1), since WoE binning convention is to have 0 as good and 1 as bad. This is important for correct WoE and IV calculations.
    if set(df[target].unique()) != {0, 1}:
        error_message = (f"Target variable: {target} has unique values {set(df[target].unique())}, but expected binary values are {{0, 1}} with convention 0=Good and 1=Bad. Please ensure the target variable is in the correct binary format before applying auto_woe_binning_numeric.")
        logger.error(error_message)
        raise ValueError(error_message)

    # Copy of Dataframe with Feature and Target
    data = df[[feature, target]].copy()
    before_drop = len(data)

    # Drop Nan rows in feature and target columns.
    # NOTE: Actually, we are raising an error if there are NULL values in the feature column, but we can still have NULL values in the target column. So, we drop rows with NULL values in either feature or target columns to ensure clean data for binning.
    data = data.dropna(subset=[feature, target])
    after_drop = len(data)

    logger.info(f"Missing rows dropped. Before={before_drop}, After={after_drop}, Dropped={before_drop - after_drop}")

    data[target] = data[target].astype(int)
    logger.info(f"Target variable {target} converted to integer type.")

    # Create initial bins using pd.qcut. The resulting bins are pandas Interval objects.
    data["_bin"] = create_initial_bins(
        df=data,
        feature=feature,
        initial_bins=initial_bins
    )
    logger.info("Initial bins created.")

    intervals = list(data["_bin"].cat.categories)
    logger.info("Initial intervals created.")

    steps_metada = {}
    # Flag to track whether the binning converged (all rules satisfied via break)
    # or stopped because the maximum iteration limit was reached.
    converged = False
    # Start the iterative merging process based on the defined rules.
    for step in range(1, max_iter + 1):
        logger.info(f"--- Iteration {step} ---")
        
        # Track which rule triggered at this step
        triggered_rule = None
        
        # Assign bins based on the current interval structure.
        data["_bin"] = assign_bins_from_intervals(
            x=data[feature],
            intervals=intervals
        )
        logger.info(f"STEP: {step} - Bins assigned based on current intervals.")

        # Calculate WoE / IV summary table based on the current binning structure.
        summary, _ = calculate_woe_iv_table(
            df=data,
            bin_col="_bin",
            target=target,
            eps=0.5,
            output_dir = None,

        )
        logger.info(f"STEP: {step} - WoE / IV summary table calculated.")

        summary = summary.sort_values("_bin").reset_index(drop=True)
        logger.info(f"STEP: {step} - Summary table sorted by bins.")

        current_iv = summary["iv"].sum()

        logger.info(f"STEP: {step} - Current bin count={len(intervals)}, Current IV={current_iv:.6f}")

        # Convert bin column to string for JSON serialization
        summary_for_metadata = summary.copy()
        summary_for_metadata["_bin"] = summary_for_metadata["_bin"].astype(str)
        
        steps_metada[step] = {
            "bin_count": len(intervals),
            "iv": current_iv,
            "triggered_rule": triggered_rule,
            "woe": summary_for_metadata.to_dict(orient="records")
        }

        logger.info(f"STEP: {step} - RULES CHECK START")

        # Detect if bins with insufficient observation ratio exist. If yes, merge the most problematic bin with its closest neighbor.
        if (summary["bin_pct"] < min_bin_pct).any() and len(intervals) > 1:
            idx = summary["bin_pct"].idxmin()

            # We find the closest neighbor to merge with based on the specified metric (e.g., bad_rate).
            merge_idx = find_closest_neighbor(
                summary=summary,
                idx=idx,
                metric="bad_rate"
            )

            triggered_rule = "Rule 1: Small bin merge"
            logger.info(f"Rule 1 triggered: small bin merge.")
            logger.info(f"STEP: {step} - Problem bin={idx}, Merge pair=({merge_idx},{merge_idx + 1})")

            # Merge the identified pair of bins and update the intervals list.
            intervals = merge_intervals(
                intervals=intervals,
                i=merge_idx
            )
            logger.info(f"STEP: {step} - Intervals merged based on Rule 1.")
            steps_metada[step]["triggered_rule"] = triggered_rule
            continue

        # Detect if bins with zero good or zero bad exist. If yes, merge the problematic bin with its closest neighbor.
        zero_mask = (summary["good"] == 0) | (summary["bad"] == 0)
        if zero_mask.any() and len(intervals) > 1:
            idx = zero_mask.idxmax()

            merge_idx = find_closest_neighbor(
                summary=summary,
                idx=idx,
                metric="bad_rate"
            )

            triggered_rule = "Rule 2: Zero good/bad merge"
            logger.info(f"Rule 2 triggered: zero good/bad merge.")
            logger.info(f"STEP: {step} - Problem bin={idx}, Merge pair=({merge_idx},{merge_idx + 1})")

            intervals = merge_intervals(
                intervals=intervals,
                i=merge_idx
            )
            logger.info(f"STEP: {step} - Intervals merged based on Rule 2.")
            steps_metada[step]["triggered_rule"] = triggered_rule
            continue
        
        # Detect monotonicity violations in bad_rate and WoE. If any violation exists, merge the closest violating pair.
        if not is_monotonic(summary["bad_rate"]) and len(intervals) > 1:
            # We find the closest violating pair to merge based on the specified metric (e.g., bad_rate).
            merge_idx = find_monotonicity_violation_pair(
                summary=summary,
                metric="bad_rate"
            )
            logger.info(f"Monotonicity violation detected in bad_rate. Merge pair index identified: {merge_idx}")

            if merge_idx is None:
                # If no violation pair is found, we fallback to merging the most similar adjacent pair to try to fix potential monotonicity issues.
                merge_idx = find_most_similar_adjacent_pair(
                    summary=summary,
                    metric="bad_rate"
                )
                logger.info(f"No monotonicity violation pair found in bad_rate. Fallback to most similar adjacent pair. Merge pair index identified: {merge_idx}")

            triggered_rule = "Rule 3: Bad Rate monotonicity merge"
            logger.info(f"Rule 3 triggered: Bad Rate monotonicity merge.")
            logger.info(f"STEP: {step} - Merge pair=({merge_idx},{merge_idx + 1})")

            intervals = merge_intervals(
                intervals=intervals,
                i=merge_idx
            )
            logger.info(f"STEP: {step} - Intervals merged based on Rule 3.")
            steps_metada[step]["triggered_rule"] = triggered_rule
            continue
        
        # Detect monotonicity violations in WoE and merge if any violation exists. This is the last step of the algorithm to ensure WoE monotonicity after fixing all bad_rate monotonicity issues.
        if not is_monotonic(summary["woe"]) and len(intervals) > 1:
            # We find the closest violating pair to merge based on the specified metric (e.g., woe).
            merge_idx = find_monotonicity_violation_pair(
                summary=summary,
                metric="woe"
            )

            if merge_idx is None:
                # If no violation pair is found, we fallback to merging the most similar adjacent pair to try to fix potential monotonicity issues.
                merge_idx = find_most_similar_adjacent_pair(
                    summary=summary,
                    metric="woe"
                )

            triggered_rule = "Rule 4: WoE monotonicity merge"
            logger.info(f"Rule 4 triggered: WoE monotonicity merge.")
            logger.info(f"STEP: {step} - Merge pair=({merge_idx},{merge_idx + 1})")

            # Merge the identified pair of bins and update the intervals list.
            intervals = merge_intervals(
                intervals=intervals,
                i=merge_idx
            )
            logger.info(f"STEP: {step} - Intervals merged based on Rule 4.")
            steps_metada[step]["triggered_rule"] = triggered_rule
            continue

        # Detect if the current bin count is greater than the allowed maximum. If yes, merge the most similar adjacent pair to reduce bin count.
        if len(intervals) > max_final_bins:
            # We find the most similar adjacent pair to merge based on the specified metric (e.g., bad_rate).
            merge_idx = find_most_similar_adjacent_pair(
                summary=summary,
                metric="bad_rate"
            )

            triggered_rule = "Rule 5: Reducing bin count"
            logger.info(f"Rule 5 triggered: reducing bin count.")
            logger.info(f"STEP: {step} - Merge pair=({merge_idx},{merge_idx + 1})")

            # Merge the identified pair of bins and update the intervals list.
            intervals = merge_intervals(
                intervals=intervals,
                i=merge_idx
            )
            logger.info(f"STEP: {step} - Intervals merged based on Rule 5.")
            steps_metada[step]["triggered_rule"] = triggered_rule
            continue

        # Iteration stopping condition: 
        # If none of the above rules are triggered. 
        # it means the current binning structure satisfies rules:
        # Rule 1: Minimum bin percentage
        # Rule 2: Good and bad existence in every bin
        # Rule 3: Bad Rate monotonicity
        # Rule 4: WoE monotonicity
        # Rule 5: Maximum bin count
        # So, we can stop the iteration and finalize the binning results.
        triggered_rule = "STOPPED: All rules satisfied"
        steps_metada[step]["triggered_rule"] = triggered_rule
        converged = True
        logger.info(f"No more merge required. Stopping at iteration={step}")
        break

    # If the loop ended without converging, it means max_iter was reached while
    # rule violations were still present. The binning did not stabilize.
    if not converged:
        logger.warning(f"Auto binning did NOT converge for feature '{feature}'. "
                       f"Reached max_iter={max_iter} while rule violations were still present. "
                       f"The final binning may still violate some quality rules and should be reviewed.")

    logger.info(f"Iterative merging process completed after {step} iterations.")
    logger.info("----FINAL BINNINGS RESULTS----")
    # Final bin assignment based on the final interval structure after all merges.
    data["_bin"] = assign_bins_from_intervals(
        x=data[feature],
        intervals=intervals
    )

    # Final WoE / IV summary table calculation based on the final binning structure.
    woe_table, metadata_of_woe = calculate_woe_iv_table(
        df=data,
        bin_col="_bin",
        target=target
    )

    # We sort the WOE table by bins to maintain the order of intervals in the final output.
    woe_table = woe_table.sort_values("_bin").reset_index(drop=True)

    # Calculate total IV for the final binned feature.
    total_iv = woe_table["iv"].sum()

    # Perform final binning quality checks based on the defined rules and assign a final status to the binned feature.
    checks, checks_formatted = check_binning_quality(
        summary=woe_table,
        min_bin_pct=min_bin_pct,
        max_bins=max_final_bins,
        min_bins=min_final_bins
    )

    # Final status assignment logic:
    if not converged:
        status = "REVIEW_NOT_CONVERGED"
        logger.warning(f"Final binning quality checks completed. Assigned status: {status} because max_iter={max_iter} was reached before all rules were satisfied.")
    elif total_iv < min_iv:
        status = "REVIEW_WEAK_VARIABLE"
        logger.warning(f"Final binning quality checks completed. Assigned status: {status} with total IV={total_iv:.6f} below min_iv={min_iv}")
    elif total_iv > max_iv:
        status = "REVIEW_POSSIBLE_LEAKAGE"
        logger.warning(f"Final binning quality checks completed. Assigned status: {status} with total IV={total_iv:.6f} above max_iv={max_iv}")
    elif all(checks.values()):
        status = "PASS"
        logger.info(f"Final binning quality checks completed. Assigned status: {status} with all checks passed.")
    else:
        status = "REVIEW"
        logger.warning(f"Final binning quality checks completed. Assigned status: {status} with some checks failed.")


    logger.info(f"Feature: {feature}, Final bins={len(woe_table)}, Total IV={total_iv:.6f}, Status={status}")

    # Convert the _bin Interval column to string before serialization, as pd.Interval objects are not JSON serializable.
    woe_table_for_json = woe_table.copy()
    woe_table_for_json["_bin"] = woe_table_for_json["_bin"].astype(str)

    auto_binning_result = {
        "feature": feature,
        "totalIv": metadata_of_woe.get("totalIv", "not available"),
        "interpretIv": metadata_of_woe.get("interpretIv", "not available"),
        "numberofBins": metadata_of_woe.get("numberofBins", "not available"),
        "woe_table": woe_table_for_json.to_dict(orient="records"), # Convert summary DataFrame to a list of dictionaries for JSON serialization
        "checks": checks_formatted,
        "status": status,
        "converged": converged, # True if all rules were satisfied, False if max_iter was reached first
        "stopIteration": step,
        "maxIter": max_iter,
        "finalIntervals": [str(interval) for interval in intervals], # Convert Interval objects to strings for JSON serialization
        "stepsMetadata": steps_metada
    }

    # Save the auto binning result to a JSON file for further analysis and reporting.
    output_path = f"./outputs/auto_binning_woe/{feature}/final_auto_binning_woe.json"
    saved_path = io_save_json(auto_binning_result, output_path)
    logger.info(f"Auto binning result saved to {saved_path}")

    # Save the final WOE table to a CSV file for easy viewing and analysis.
    csv_output_path = f"./outputs/auto_binning_woe/{feature}/final_woe_table.csv"
    saved_path = io_save_dataframe_as_csv(woe_table, csv_output_path)
    logger.info(f"Final WOE table saved to {saved_path}")

    # Log initial parameters and final results in a structured format for better readability and analysis.
    logger.info("=" * 50)
    logger.info(f"INITIALIZE PARAMETERS")
    logger.info(f"Feature:..................... {feature}")
    logger.info(f"Target:...................... {target}")
    logger.info(f"Initial Bins:................ {initial_bins}")
    logger.info(f"Minimum Bin Percentage:...... {min_bin_pct}")
    logger.info(f"Maximum Final Bins:.......... {max_final_bins}")
    logger.info(f"Minimum IV:.................. {min_iv}")
    logger.info(f"Maximum IV:.................. {max_iv}")
    logger.info(f"Maximum Iterations:.......... {max_iter}")
    logger.info("=" * 50)

    logger.info("=" * 50)
    logger.info("MERGE STEPS (binning flow)")
    logger.info("")
    total_steps = len(steps_metada)
    for idx, (step, metadata) in enumerate(steps_metada.items()):
        is_last = idx == total_steps - 1
        connector = "└──" if is_last else "├──"
        pipe = "    " if is_last else "│   "
        marker = "[done]" if is_last else "[fail]"
        prefix = "Stopped:" if is_last else "Failed:"
        rule_text = metadata['triggered_rule']
        if rule_text.startswith("STOPPED: "):
            rule_text = rule_text[len("STOPPED: "):]
        logger.info(f"{connector} {marker} Step {step}  -  Bins: {metadata['bin_count']:>3}  -  IV: {metadata['iv']:.6f}")
        logger.info(f"{pipe}      -> {prefix} {rule_text}")
    logger.info("=" * 50)

    logger.info("=" * 50)
    logger.info("AUTO BINNING RESULTS")
    logger.info(f"Stopping Iteration:............... {step}")
    logger.info(f"Feature Name:..................... {feature}")
    logger.info(f"Final Bin Count:.................. {len(woe_table)}")
    logger.info(f"Total Information Value (IV):..... {total_iv:.6f}")
    logger.info(f"IV Interpretation:................ {interpret_iv(total_iv)}")
    logger.info(f"Binning Status:................... {status}")
    logger.info("-" * 50)
    logger.info("WoE Summary Table:")
    logger.info(f"\n{woe_table.to_string(index=False)}\n")
    logger.info("-" * 50)
    logger.info("-" * 50)
    logger.info("Quality Check Results:")
    for check_name, check_result in checks_formatted.items():
        logger.info(f"  {check_name}: {check_result}")
    logger.info("-" * 50)

    logger.info(f"Auto binning completed successfully for feature: '{feature}'")
    logger.info("=" * 50)

    return auto_binning_result


if __name__ == "__main__":
    # # Generate Sample Data to test calculate_woe_iv_table function
    # data = {
    #     "feature": [18, 22, 25, 30, 35, 40, 45, 50, 55, 60],
    #     "target": [0, 0, 1, 0, 1, 0, 1, 0, 1, 0]
    # }
    # df = pd.DataFrame(data)
    # df["bin"] = pd.qcut(df["feature"], q=3)
    # woe_iv_table, metadata = calculate_woe_iv_table(
    #     df, 
    #     bin_col="bin", 
    #     target="target", 
    #     eps=0.5, 
    #     output_dir="./outputs/auto_binning_woe"
    #     )

    # # Generate Sample Data to test create_initial_bins function
    # df_bins = pd.DataFrame({
    #     "feature": [18, 22, 25, 30, 35, 40, 45, 50, 55, 60]
    # })
    # initial_bins = create_initial_bins(df_bins, feature="feature", initial_bins=3)

    # # Generate Sample Data Series to test create_initial_bins function with series input
    # series_bins = pd.Series([18, 22, 25, 30, 35, 40, 45, 50, 55, 60], name="feature_series")
    # initial_bins_from_series = create_initial_bins(df_bins, feature=None, series=series_bins, initial_bins=3)

    # # Generate Sample Data to test merge_intervals function
    # intervals = [
    #     pd.Interval(18, 25, closed="right"),
    #     pd.Interval(25, 35, closed="right"),
    #     pd.Interval(35, 50, closed="right"),
    #     pd.Interval(50, 80, closed="right"), # We send this index to be merged with the next one
    #     pd.Interval(80, 100, closed="right"),
    #     pd.Interval(100, 150, closed="right")
    # ]
    # # Saying that merge intervals at index 3, which means we want to merge intervals[3] and intervals[4], which are (50, 80] and (80, 100]
    # merged_intervals = merge_intervals(intervals, i=3)

    # # Generate Sample Data to test assign_bins_from_intervals function
    # x = pd.Series([18, 22, 25, 30, 35, 40, 45, 50, 55, 60])
    # intervals_for_assignment = [
    #     pd.Interval(18, 25, closed="right"),
    #     pd.Interval(25, 50, closed="right"),
    #     pd.Interval(50, 80, closed="right"),
    #     pd.Interval(80, 100, closed="right")
    # ]
    # assigned_bins = assign_bins_from_intervals(x, intervals_for_assignment)

    # # Generate Sample Data to test find_closest_neighbor function
    # summary = pd.DataFrame({
    #     "bin": ["Bin A", "Bin B", "Bin C"],
    #     "bad_rate": [0.1, 0.11, 0.3]
    # })

    # closest_neighbor_idx = find_closest_neighbor(summary, idx=1, metric="bad_rate")

    # # Generate Sample Data to test find_most_similar_adjacent_pair function
    # summary_for_similarity = pd.DataFrame({
    #     "bin": ["Bin A", "Bin B", "Bin C"],
    #     "bad_rate": [0.1, 0.11, 0.3]
    # })

    # most_similar_adjacent_pair_idx = find_most_similar_adjacent_pair(summary_for_similarity, metric="bad_rate")

    # # Generate Sample Data to test find_monotonicity_violation_pair function
    # summary_for_monotonicity = pd.DataFrame({
    #     "bin": ["Bin A", "Bin B", "Bin C", "Bin D"],
    #     "bad_rate": [0.05, 0.1, 0.08, 0.2]
    # })

    # monotonicity_violation_pair_idx = find_monotonicity_violation_pair(summary_for_monotonicity, metric="bad_rate")

    # # Generate Sample Data to test check_binning_quality function
    # summary_for_quality_check = pd.DataFrame({
    #     "bin": ["Bin A", "Bin B", "Bin C"],
    #     "total": [100, 100, 100],
    #     "good": [90, 89, 70],
    #     "bad": [10, 11, 30],
    #     "bad_rate": [0.1, 0.11, 0.3],
    #     "bin_pct": [0.33, 0.33, 0.34],
    #     "woe": [-0.405465, -0.182322, 0.405465],
    #     "iv": [0.004054, 0.000328, 0.016218]
    # })

    # quality_checks = check_binning_quality(summary_for_quality_check, min_bin_pct=0.05, max_bins=5)

    # # Generate Sample Data (100 Rows) to test auto_woe_binning_numeric function
    # # Feature and target are logically related: as feature increases, probability of target=1 increases
    # np.random.seed(42)
    # feature_data = np.random.uniform(18, 250, 1000)
    # # Use sigmoid function to create logical relationship: higher feature → higher probability of bad (1)
    # probabilities = 1 / (1 + np.exp(-(feature_data - 59) / 15))  # Sigmoid centered around 59
    # target_data = np.array([np.random.choice([0, 1], p=[1-p, p]) for p in probabilities])
    
    # df_for_auto_binning = pd.DataFrame({
    #     "feature": feature_data,
    #     "target": target_data
    # })

    # auto_binning_result = auto_woe_binning_numeric(
    #     df=df_for_auto_binning,
    #     feature="feature",
    #     target="target",
    #     initial_bins=20, # We start with 20 initial bins to allow the algorithm to have enough granularity to work with and merge as needed based on the defined rules.
    #     min_bin_pct=0.05, # We set the minimum bin percentage to 5% to ensure that each bin has a sufficient number of observations to be statistically meaningful.
    #     max_final_bins=10, # We set the maximum final bins to 10 to align with common scorecard binning practices and to ensure that the final output is interpretable and actionable.
    #     min_final_bins=3, # We set the minimum final bins to 3 to ensure that the final binning output has enough granularity to capture meaningful patterns in the data while avoiding oversimplification.
    #     min_iv=0.02, # We set the minimum IV to 0.02 to flag features that may be too weak for predictive modeling and may require further review or exclusion from the model.
    #     max_iv=0.50, # We set the maximum IV to 0.50 to flag features that may have too strong of a relationship with the target variable, which could indicate potential data leakage or overfitting issues that require further investigation.
    #     max_iter=25 # We set the maximum iterations to 25 to allow the algorithm to perform enough merging steps to satisfy the defined rules while preventing infinite loops in cases where the rules cannot be satisfied within a reasonable number of merges.
    # )

    # Test with UCI Credit Card Dataset
    metadata_path = "inputs/sample/datatypes.json"
    with open(metadata_path, "r") as f:
        metadata = json.load(f)
    column_dtypes = metadata.get("column_dtypes", {})
    # Get the sample data
    input_csv_path = "inputs/sample/uci_credit_card_dataset.csv"
    df = pd.read_csv(input_csv_path, dtype=column_dtypes)
    # Log Column names and data types
    for column in df.columns:
        logger.info(f"Column: {column}: {column_dtypes.get(column, 'Unknown')} | Unique Values: {df[column].nunique()}")
    logger.info("Sample data loaded successfully.")

    for col in df.columns:
        if col not in ["TARGET"]:
            logger.info(f"Processing column: {col}")
            if is_numeric_dtype(df[col]):
                logger.info(f"Applying auto WoE binning to numeric feature: {col}")
                result = auto_woe_binning_numeric(
                    df=df,
                    feature=col,
                    target="TARGET",
                    initial_bins=20,
                    min_bin_pct=0.05,
                    max_final_bins=10,
                    min_final_bins=3,
                    min_iv=0.02,
                    max_iv=0.50,
                    max_iter=25
                )
